spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
    show-sql: true
server:
  port: 7000
  servlet:
    context-path: /payment
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka